In [1]:
import torch
import numpy as np

In [2]:
w1 = torch.randn([10, 2],requires_grad=True)
b1 = torch.randn(10,requires_grad=True)
w2 = torch.randn([10, 10],requires_grad=True)
b2 = torch.randn(10,requires_grad=True)
w3 = torch.randn([1, 10],requires_grad=True)
b3 = torch.randn(1,requires_grad=True)

# auto

In [3]:
x = torch.randn(2)
x

tensor([ 1.0458, -0.5822])

In [4]:
x.requires_grad_(True)
x

tensor([ 1.0458, -0.5822], requires_grad=True)

In [5]:
y = (x[0]**2 + x[1]**2) / 2
y

tensor(0.7163, grad_fn=<DivBackward0>)

In [6]:
h1 = torch.matmul(w1, x) + b1
h1_activate = torch.sigmoid(h1)
h2 = torch.matmul(w2, h1_activate) + b2
h2_activate = torch.sigmoid(h2)
pred = torch.matmul(w3, h2_activate) + b3
pred

tensor([0.8695], grad_fn=<AddBackward0>)

In [7]:
h1

tensor([ 1.3654,  1.6386,  0.1854, -1.4092,  0.3450,  0.1500, -1.5090,  1.5910,
        -0.1537,  0.5695], grad_fn=<AddBackward0>)

In [8]:
h1_activate

tensor([0.7966, 0.8373, 0.5462, 0.1964, 0.5854, 0.5374, 0.1811, 0.8308, 0.4616,
        0.6386], grad_fn=<SigmoidBackward>)

In [9]:
loss = (pred-y)**2
loss

tensor([0.0235], grad_fn=<PowBackward0>)

In [10]:
loss.backward()

In [11]:
print(w1.grad)
print(b1.grad)
print(w2.grad)
print(b2.grad)
print(w3.grad)
print(b3.grad)

tensor([[ 0.0130, -0.0072],
        [ 0.0206, -0.0115],
        [-0.0067,  0.0037],
        [ 0.0366, -0.0204],
        [-0.0357,  0.0199],
        [-0.1249,  0.0695],
        [-0.0142,  0.0079],
        [-0.0370,  0.0206],
        [ 0.0668, -0.0372],
        [ 0.0099, -0.0055]])
tensor([ 0.0124,  0.0197, -0.0064,  0.0350, -0.0341, -0.1194, -0.0136, -0.0354,
         0.0638,  0.0094])
tensor([[ 0.0137,  0.0144,  0.0094,  0.0034,  0.0100,  0.0092,  0.0031,  0.0142,
          0.0079,  0.0109],
        [ 0.1502,  0.1578,  0.1030,  0.0370,  0.1104,  0.1013,  0.0341,  0.1566,
          0.0870,  0.1204],
        [ 0.0034,  0.0035,  0.0023,  0.0008,  0.0025,  0.0023,  0.0008,  0.0035,
          0.0019,  0.0027],
        [-0.0183, -0.0192, -0.0125, -0.0045, -0.0134, -0.0123, -0.0042, -0.0191,
         -0.0106, -0.0147],
        [ 0.0028,  0.0029,  0.0019,  0.0007,  0.0020,  0.0019,  0.0006,  0.0029,
          0.0016,  0.0022],
        [-0.0827, -0.0870, -0.0567, -0.0204, -0.0608, -0.0558, -0.0

# my

In [12]:
def sigmoid_prime(z):
  return sigmoid(z) * (1-sigmoid(z))
def sigmoid(z):
  return 1.0/(1.0 + np.exp(-z))

In [13]:
w_list = [w1.detach().numpy(), w2.detach().numpy(), w3.detach().numpy()]
b_list = [b1.detach().numpy(), b2.detach().numpy(), b3.detach().numpy()]

In [14]:
w_list

[array([[ 0.11520769, -1.4604033 ],
        [ 1.2982341 ,  0.17773491],
        [-0.7639063 , -1.7555146 ],
        [-0.85020703, -0.79943573],
        [ 0.5389087 , -0.50550324],
        [-0.14215304,  1.4952424 ],
        [-0.86971295,  0.13324322],
        [ 0.9634977 , -1.4129666 ],
        [ 0.65819687,  0.7188048 ],
        [ 0.51375353,  0.857849  ]], dtype=float32),
 array([[ 8.95909131e-01,  5.83758175e-01, -1.11530709e+00,
          8.15845355e-02, -2.65208054e+00, -7.04577863e-01,
         -8.36997852e-02,  7.07591236e-01,  2.41884303e+00,
          7.34549105e-01],
        [ 7.22644687e-01,  3.75827223e-01,  3.56234938e-01,
          4.51898962e-01, -1.11085856e+00, -1.76100695e+00,
          1.31211802e-01, -1.31856549e+00,  2.20971918e+00,
          9.56653476e-01],
        [-2.45880708e-01,  2.22406411e+00,  4.28827614e-01,
         -3.10494423e-01,  7.36873746e-02, -2.87312686e-01,
         -2.65449500e+00,  8.57233763e-01,  2.65988439e-01,
          1.12840936e-01],
  

In [15]:
x = x.detach().numpy()
y = y.detach().numpy()

In [16]:
# grad list
nabla_b = [np.zeros(b.shape) for b in b_list]
nabla_w = [np.zeros(w.shape) for w in w_list]


In [17]:
# forward propagation
z1 = np.dot(w_list[0], x) + b_list[0]
z1_act = sigmoid(z1)
z2 = np.dot(w_list[1], z1_act) + b_list[1]
z2_act = sigmoid(z2)
z3 = np.dot(w_list[2], z2_act) + b_list[2]
z3

array([0.8694965], dtype=float32)

In [18]:
# grad for last layer
loss = (z3 - y)**2
delta = 2 * (z3 - y)
nabla_b[-1] = delta
nabla_w[-1] = np.dot(delta, z2_act.transpose().reshape((1,10)))

In [19]:
w_list[-2+1].shape

(1, 10)

In [20]:
# grad for second layer
delta = np.dot(w_list[-2+1].transpose(), delta) * sigmoid_prime(z2)
nabla_b[-2] = delta
nabla_w[-2] = np.dot(delta.reshape((10,1)), z1_act.transpose().reshape((1, 10)))

In [21]:
# grad for first layer
delta = np.dot(w_list[-3+1].transpose(), delta) * sigmoid_prime(z1)
nabla_b[-3] = delta
nabla_w[-3] = np.dot(delta.reshape((10, 1)), x.transpose().reshape((1, 2)))

In [22]:
nabla_b

[array([ 0.01242867,  0.01968558, -0.006363  ,  0.03499979, -0.03409869,
        -0.11943121, -0.01355892, -0.03541619,  0.06384694,  0.00944304],
       dtype=float32),
 array([ 0.01714191,  0.18849985,  0.0042168 , -0.02296408,  0.00349468,
        -0.10386669, -0.03472225, -0.00118987, -0.07835759,  0.01610759],
       dtype=float32),
 array([0.30638027], dtype=float32)]

In [23]:
nabla_w

[array([[ 0.01299736, -0.00723649],
        [ 0.02058633, -0.01146177],
        [-0.00665415,  0.0037048 ],
        [ 0.03660127, -0.02037834],
        [-0.03565894,  0.01985368],
        [-0.124896  ,  0.06953783],
        [-0.01417933,  0.00789457],
        [-0.03703672,  0.02062078],
        [ 0.06676837, -0.03717436],
        [ 0.00987513, -0.00549813]], dtype=float32),
 array([[ 0.01365597,  0.0143537 ,  0.00936325,  0.00336589,  0.01003513,
          0.00921245,  0.00310414,  0.01424084,  0.00791341,  0.01094763],
        [ 0.15016699,  0.15783955,  0.10296238,  0.03701274,  0.11035067,
          0.10130415,  0.03413443,  0.15659846,  0.0870193 ,  0.12038487],
        [ 0.00335928,  0.00353092,  0.0023033 ,  0.00082799,  0.00246858,
          0.0022662 ,  0.0007636 ,  0.00350315,  0.00194665,  0.00269305],
        [-0.01829416, -0.01922888, -0.01254344, -0.00450909, -0.01344352,
         -0.01234143, -0.00415844, -0.01907768, -0.01060117, -0.01466594],
        [ 0.00278401,  0.00

In [24]:
w1.grad

tensor([[ 0.0130, -0.0072],
        [ 0.0206, -0.0115],
        [-0.0067,  0.0037],
        [ 0.0366, -0.0204],
        [-0.0357,  0.0199],
        [-0.1249,  0.0695],
        [-0.0142,  0.0079],
        [-0.0370,  0.0206],
        [ 0.0668, -0.0372],
        [ 0.0099, -0.0055]])

In [25]:
nabla_w[0]

array([[ 0.01299736, -0.00723649],
       [ 0.02058633, -0.01146177],
       [-0.00665415,  0.0037048 ],
       [ 0.03660127, -0.02037834],
       [-0.03565894,  0.01985368],
       [-0.124896  ,  0.06953783],
       [-0.01417933,  0.00789457],
       [-0.03703672,  0.02062078],
       [ 0.06676837, -0.03717436],
       [ 0.00987513, -0.00549813]], dtype=float32)